version: '3'
services:

    phpminds-php:
        build: docker/php
        restart: always
        volumes:
            - .:/app
        environment:
            PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
